"""Initial NIDAR RescueSwarm GCS schema.

Baseline migration. It enables PostGIS and then creates the whole schema from
the SQLAlchemy metadata, which guarantees the deployed database matches the
models exactly -- important for the geometry columns, whose spatial indexes
geoalchemy2 attaches during ``create_all``.

Every migration after this one is a normal autogenerated diff:

    alembic revision --autogenerate -m "describe the change"

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-08
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
from app.models import Base

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()

    # PostGIS carries every position, sector, route and geofence in this
    # system. Without it nothing below can be created.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    Base.metadata.create_all(bind=bind)

    # A partial unique index rather than a table constraint: a survivor may
    # accumulate many finished delivery tasks over a mission, but never two
    # live ones -- which is what stops two aircraft being sent to one person.
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_delivery_tasks_active_survivor
        ON delivery_tasks (survivor_id)
        WHERE state IN (
            'ASSIGNED', 'ROUTE_PLANNED', 'EN_ROUTE', 'AT_TARGET',
            'DELIVERY_INITIATED', 'RETURNING'
        )
        """
    )

    # One active link session per aircraft at a time.
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_drone_connections_open
        ON drone_connections (drone_uuid)
        WHERE closed_at IS NULL
        """
    )

    # One standing alert per deduplication key, so a drone sitting at 24%
    # battery produces one alert rather than one per safety-engine cycle.
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_alerts_active_dedupe
        ON alerts (dedupe_key)
        WHERE active IS TRUE
        """
    )

    # Telemetry is the highest-volume table by far; this index backs the
    # "latest sample per aircraft" lookup used on every dashboard refresh.
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_telemetry_samples_drone_time_desc
        ON telemetry_samples (drone_uuid, sampled_at DESC)
        """
    )


def downgrade() -> None:
    bind = op.get_bind()
    op.execute("DROP INDEX IF EXISTS ix_telemetry_samples_drone_time_desc")
    op.execute("DROP INDEX IF EXISTS uq_alerts_active_dedupe")
    op.execute("DROP INDEX IF EXISTS uq_drone_connections_open")
    op.execute("DROP INDEX IF EXISTS uq_delivery_tasks_active_survivor")
    Base.metadata.drop_all(bind=bind)
